ext:
  group: ${ext.group}
  appName: ${ext.appName}
  version: ${ext.version}

server:
  port: 8888
  shutdown: graceful

spring:
  application:
    name: ${ext.appName}

---
spring:
  profiles:
    active: local

---
spring:
  profiles:
    active: docker
